from dataclasses import replace
import math
from pathlib import Path
import tempfile
import unittest

import numpy as np

from distribution_propagator.config import Config
from distribution_propagator.orbit import from_keplerian, to_cartesian
from distribution_propagator.sampling import MT19937_64, sample_initial


class SamplingTests(unittest.TestCase):
    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory()
        self.addCleanup(self.tmp.cleanup)
        self.directory = Path(self.tmp.name)

    def empirical(self, rows):
        path = self.directory/'samples.csv'
        np.savetxt(path, rows, delimiter=',', fmt='%.17g')
        return path

    def test_standard_mt19937_64_and_cpp_reference(self):
        # Generated by the adjacent reproducible C++ oracle, including several
        # state-transition boundaries that detect superficially correct engines.
        fixture = Path(__file__).parent/'data'/'cpp_sampling_reference.csv'
        references, samples = {}, []
        for line in fixture.read_text().splitlines():
            row = line.split(',')
            if row[0] == 'rng':
                references[int(row[1])] = int(row[2])
            else:
                samples.append([float(v) for v in row[1:]])
        rng = MT19937_64(5489)
        for index in range(1000):
            actual = rng()
            if index in references:
                self.assertEqual(actual, references[index])
        actual = sample_initial(Config(samples=5, threads=1))
        # libm implementations may differ at a last bit between platforms.
        np.testing.assert_allclose(actual, samples, rtol=2e-15, atol=1e-15)

    def test_gaussian_moments_and_prefix(self):
        sigma = np.array([50000, .001, .002, .0002, .0003, .005])
        covariance = np.diag(sigma*sigma)
        covariance[0,5] = covariance[5,0] = -.65*sigma[0]*sigma[5]
        covariance[1,2] = covariance[2,1] = .35*sigma[1]*sigma[2]
        c = Config(samples=20000, covariance=covariance, threads=1)
        sample = sample_initial(c)
        standardized = (sample-c.nominal)/sigma
        self.assertTrue(np.all(np.abs(standardized.mean(axis=0)) < 6/math.sqrt(c.samples)))
        expected = covariance/np.outer(sigma, sigma)
        tolerance = 6*np.sqrt((1+expected**2)/(c.samples-1))
        self.assertTrue(np.all(np.abs(np.cov(standardized, rowvar=False)-expected) < tolerance))
        prefix = sample_initial(replace(c, samples=40))
        np.testing.assert_array_equal(prefix, sample[:40])
        np.testing.assert_array_equal(sample_initial(replace(c, samples=40, threads=7)), prefix)
        self.assertFalse(np.array_equal(sample_initial(replace(c, samples=40, seed=c.seed+1)), prefix))

    def test_zero_variance_axes_remain_exact(self):
        c = Config(samples=100, covariance=np.diag([0,1e-6,0,1e-8,0,1e-6]), threads=1)
        sample = sample_initial(c)
        np.testing.assert_array_equal(sample[:,[0,2,4]], np.broadcast_to(c.nominal[[0,2,4]], (100,3)))
        self.assertNotEqual(sample[0,1], sample[-1,1])

    def test_cartesian_gaussian_moments_after_conversion(self):
        sigma = np.array([50,30,20,.03,.02,.01])
        covariance = np.diag(sigma*sigma)
        covariance[0,4] = covariance[4,0] = .4*sigma[0]*sigma[4]
        c = Config(samples=10000, covariance=covariance, uncertainty_coordinates='cartesian', threads=1)
        nominal = to_cartesian(c.nominal, c.backend.mu)
        cartesian = np.array([to_cartesian(e, c.backend.mu) for e in sample_initial(c)])
        z = (cartesian-nominal)/sigma
        expected = covariance/np.outer(sigma,sigma)
        self.assertTrue(np.all(np.abs(z.mean(axis=0)) < 6/math.sqrt(c.samples)))
        tolerance = 6*np.sqrt((1+expected*expected)/(c.samples-1))
        self.assertTrue(np.all(np.abs(np.cov(z, rowvar=False)-expected) < tolerance))

    def test_empirical_rtn_fixed_epoch_velocity_convention(self):
        a = 26560000.0
        offsets = np.array([[10,20,30,.1,.2,.3], [-40,50,-60,-.4,.5,-.6]])
        c = Config(nominal=from_keplerian(a, 0, math.pi/2, 0, 0, 0), uncertainty_coordinates='rtn',
                   empirical_samples_csv=self.empirical(offsets), threads=1)
        sample = sample_initial(c)
        speed = math.sqrt(c.backend.mu/a)
        for elements, d in zip(sample, offsets):
            expected = [a+d[0], -d[2], d[1], d[3], -d[5], speed+d[4]]
            actual = to_cartesian(elements, c.backend.mu)
            np.testing.assert_allclose(actual[:3], expected[:3], atol=3e-7, rtol=0)
            np.testing.assert_allclose(actual[3:], expected[3:], atol=3e-10, rtol=0)

    def test_empirical_cartesian_lifts_phase_to_nominal_branch(self):
        a = 26560000.0
        c = Config(nominal=np.array([a,0,0,0,0,4*math.tau]), uncertainty_coordinates='cartesian', threads=1)
        speed = math.sqrt(c.backend.mu/a)
        states = [[a*math.cos(p), a*math.sin(p), 0, -speed*math.sin(p), speed*math.cos(p), 0] for p in [-.01,.01]]
        c.empirical_samples_csv = self.empirical(states)
        sample = sample_initial(c)
        np.testing.assert_allclose(sample[:,5], 4*math.tau+np.array([-.01,.01]), atol=2e-14, rtol=0)

    def test_empirical_elements_are_absolute_and_preserve_turns(self):
        rows = [[26560000,.01,.02,.1,.2,7.1], [26561000,.011,.021,.11,.21,7.2]]
        c = Config(empirical_samples_csv=self.empirical(rows), threads=1)
        np.testing.assert_array_equal(sample_initial(c), rows)

    def test_invalid_posterior_is_not_clipped_or_redrawn(self):
        c = Config(samples=10, covariance=np.diag([1e20,0,0,0,0,0]), threads=1)
        with self.assertRaisesRegex(ValueError, 'samples are not clipped or redrawn'):
            sample_initial(c)
        c = Config(empirical_samples_csv=self.empirical([[26560000,0,0,0,0,0],[-1,0,0,0,0,0]]), threads=1)
        with self.assertRaisesRegex(ValueError, 'Invalid empirical row 2'):
            sample_initial(c)

    def test_memory_preflight_gaussian_and_empirical(self):
        c = Config(max_memory_mb=.001, threads=1)
        with self.assertRaisesRegex(ValueError, 'memory'):
            sample_initial(c)
        c.empirical_samples_csv = self.empirical([c.nominal, c.nominal])
        with self.assertRaisesRegex(ValueError, 'memory'):
            sample_initial(c)
        c = Config(samples=2, visual_samples=0, write_html=False, phase_bins=100000,
                   duration_days=1000, output_step_days=.1, max_memory_mb=50, threads=1)
        with self.assertRaisesRegex(ValueError, 'memory'):
            sample_initial(c)


if __name__ == '__main__':
    unittest.main()
